services:
  postgres:
    mem_limit: 768m

  redis:
    mem_limit: 128m

  zookeeper:
    mem_limit: 256m

  kafka:
    mem_limit: 640m
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_K3D:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,PLAINTEXT_K3D://0.0.0.0:39092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:${KAFKA_HOST_PORT:-29092},PLAINTEXT_K3D://host.k3d.internal:${KAFKA_K3D_HOST_PORT:-39092}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "${KAFKA_HOST_PORT:-29092}:29092"
      - "${KAFKA_K3D_HOST_PORT:-39092}:39092"
