package com.finrisk.radar.risk;

public enum CreditEventType {
  NEGATIVE_OUTLOOK,
  CREDIT_RATING_DOWNGRADE,
  SPECULATIVE_GRADE_ENTRY,
  CREDIT_RATING_CCC_OR_BELOW,
  CREDIT_RATING_D,
  FUNDING_FAILURE,
  RIGHTS_OFFERING_FAILURE,
  BOND_ISSUANCE_FAILURE,
  REFINANCING_FAILURE,
  PAYMENT_DELAY,
  PAYMENT_DEFAULT,
  EVENT_OF_DEFAULT,
  ACCELERATION_EVENT,
  CROSS_DEFAULT,
  GUARANTEE_CALL,
  REHABILITATION_FILED,
  BANKRUPTCY_FILED,
  LIQUIDITY_CRISIS,
  FX_HEDGE_STRESS,
  CASH_TRAP_TRIGGERED,
  DIVIDEND_REDUCTION,
  LTV_COVENANT_BREACH
}
