package com.finrisk.radar.backtest;

public enum CustomConditionType {
	RSI_LESS_THAN,
	PRICE_ABOVE_MA,
	MA_CROSS_UP,
	BOLLINGER_LOWER_TOUCH,
	MACD_GOLDEN_CROSS,
	VOLUME_SPIKE,
	BREAKOUT,
	MA_DISCOUNT,
	DONCHIAN_HIGH_BREAKOUT,
	MOMENTUM_POSITIVE,
	RSI_GREATER_THAN,
	PRICE_BELOW_MA,
	MA_CROSS_DOWN,
	BOLLINGER_UPPER_TOUCH,
	MACD_DEAD_CROSS,
	STOP_LOSS,
	TAKE_PROFIT,
	TRAILING_STOP,
	MA_PREMIUM,
	DONCHIAN_LOW_BREAKDOWN,
	MOMENTUM_NEGATIVE
}
