apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application-podmonitor.yaml
  - kafka-exporter.yaml
  - redis-exporter.yaml
  - exporter-servicemonitors.yaml
configMapGenerator:
  - name: finrisk-kubernetes-dashboard
    namespace: monitoring
    files:
      - dashboards/finrisk-kubernetes-overview.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
