spring:
  application:
    name: backend

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  health:
    redis:
      enabled: false
    kafka:
      enabled: false
