package com.finrisk.radar.notification;

public enum NotificationType {
  BACKTEST_COMPLETED,
  BACKTEST_FAILED,
  REPORT_COMPLETED,
  REPORT_FAILED,
  HIGH_RISK_SIGNAL_DETECTED,
  PAYMENT_COMPLETED,
  PAYMENT_CANCELED,
  PAYMENT_FAILED,
  FSD_REVIEW_REQUIRED,
  PAYMENT_RECOVERY_REQUIRED
}
