package com.finrisk.radar.risk.engine;

public enum RiskRuleType {
  DEBT_RATIO,
  INTEREST_COVERAGE,
  OPERATING_CASH_FLOW,
  NET_LOSS,
  MATURITY_CONCENTRATION,
  SHORT_TERM_DEBT_DEPENDENCY,
  CASH_MATURITY_COVERAGE,
  LIQUIDITY_COVERAGE,
  MATURITY_TREND,
  PRICE_DROP,
  VOLATILITY_SPIKE,
  VOLUME_ANOMALY,
  CREDIT_EVENT,
  GROUP_CONTAGION
}
